#!/usr/bin/env bash
set -eu

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

log() {
  printf '%s\n' "$*"
}

read_env_value() {
  key="$1"
  default_value="$2"
  if [ -f .env ]; then
    value="$(awk -F= -v key="$key" '$1 == key {print substr($0, length(key) + 2)}' .env | tail -n 1)"
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return
    fi
  fi
  printf '%s' "$default_value"
}

detect_tailscale_ip() {
  if [ -n "${SENTINEL_BIND_IP:-}" ]; then
    printf '%s' "$SENTINEL_BIND_IP"
    return
  fi
  if command -v tailscale >/dev/null 2>&1; then
    tailscale ip -4 2>/dev/null | head -n 1
    return
  fi
}

if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    cp .env.example .env
    log "Created .env from .env.example"
  else
    log "Missing .env and .env.example"
    exit 1
  fi
fi

AGENT_PORT="${AGENT_PORT:-$(read_env_value AGENT_PORT 8443)}"
TAILSCALE_IP="$(detect_tailscale_ip)"

if [ -z "$TAILSCALE_IP" ]; then
  log "Could not detect a Tailscale IPv4 address."
  log "Set SENTINEL_BIND_IP and run again, for example:"
  log "  SENTINEL_BIND_IP=100.x.x.x bash scripts/configure-agent.sh"
  exit 1
fi

cat > docker-compose.override.yml <<YAML
# Generated by scripts/configure-agent.sh.
# Docker Compose loads this file automatically.
services:
  sentinel-agent:
    ports:
      - "${TAILSCALE_IP}:${AGENT_PORT}:${AGENT_PORT}"
YAML

log "Wrote docker-compose.override.yml"
log "Agent will bind to:"
log "  http://127.0.0.1:${AGENT_PORT}"
log "  http://${TAILSCALE_IP}:${AGENT_PORT}"
